### PR TITLE
add "like" functionality

### PR DESCRIPTION
**Pull request by orenlande**
simple addition makes great improvement.

use it like: users/list?first_name[like]=John, will result in

SELECT ... WHERE ... first_name LIKE '%John%'

### CODE REVIEW

**Comment by mehdi-fathi** [comment]
Thanks for your contribution 👍. I  will release that in the next version. I should write the unit test for new features.

**Comment by mehdi-fathi** [comment]
@orenlande when I'm writing a test for this feature suddenly I thought a better idea. Actually we can make this URL: users/list?first_name[like]=%John%  

for create char like in query string

SELECT ... WHERE ... first_name LIKE '%John%'
sometimes you want like custom wherein the query. users want to the freedom in implement features

**Comment by orenlande** [comment]
It makes sense, the only argument I can think about it's "dirty" URL request.

I'll let you handle the change.

**Comment by mehdi-fathi** [comment]
@orenlande no it's not dirty URL. ok, I implement this feature.

**Pull request merged**
